name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: DÃ©ploiement sur OVH MutualisÃ©
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš RÃ©cupÃ©ration du code (Checkout)
        uses: actions/checkout@v4

      - name: ðŸ“‚ DÃ©ploiement FTP vers OVH
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.OVH_FTP_SERVER }}
          username: ${{ secrets.OVH_FTP_USERNAME }}
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          server-dir: /www/sasnio/
          # Note : Si la connexion FTP d'OVH pointe dÃ©jÃ  directement sur /home/devinfe/, 
          # vous devrez peut-Ãªtre changer la ligne ci-dessus en : server-dir: /www/sasnio/ ou www/sasnio/
