name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: DÃ©ploiement sur OVH MutualisÃ©
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš RÃ©cupÃ©ration du code (Checkout)
        uses: actions/checkout@v4

      - name: ðŸ“‚ DÃ©ploiement FTP vers OVH
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.OVH_FTP_SERVER }}
          username: ${{ secrets.OVH_FTP_USERNAME }}
          password: ${{ secrets.OVH_FTP_PASSWORD }}
          port: 990
          protocol: ftp
          server-dir: /www/sasnio/
          dangerously-allow-unauthorized: true
